### ISSUE TITLE
Create Project Reset Mutation

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#102]
API for reseting the project state, it could just be part of the project API

## Describe the feature few words
Add an API endpoint for reseting the project state

## What will be the end result of this change?
We can reset the project state

## Is there any previous work that needs to be completed before making this change?
N/A

## Which components will this change effect?
- API schema

**Comment by bthaile** [comment]
Would this delete all deployed contracts? This feature has been requested.
