### ISSUE TITLE
Improve Playground error handling

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#122]
Playground API can (simply said) produce two types of errors. 
- The first type of error is "input" errors or "user" errors, meaning they are related to misuse of the API by the user or client app.
- The second type of error are logical errors, those shouldn't be reached unless there's a bug

The problem is we currently treat both types of errors the same and report the to the sentry and to the user.

We should only report the user errors to the user and not to Sentry, and the second type we should report to sentry and we should only return to the user a generic error response saying something like: "Error occurred, we are looking into it".

Example of logical error (bug) that shouldn't occur would be:
https://github.com/onflow/flow-playground-api/blob/master/blockchain/emulator.go#L216
- Could be not handled and bubbled up

Example of user error that can occur is:
https://github.com/onflow/flow-playground-api/blob/master/controller/projects.go#L114

The proposed solution is to have a special error type called "UserError" and return those errors whenever there's a user error. Then refactor the error handler middleware to try and see if the type is "UserError" and if so return the error to the user, otherwise report the error to sentry and return a generic error.

We also need to set correct HTTP status for each, in case of user errors should be 4XX and in case of logical error it should be 5XX.

**Comment by fotescodev** [comment]
Need Problem Statement / Acceptance Criteria

**Comment by sideninja** [comment]
@fotescodev done

**Comment by DylanTinianov** [comment]
We need a list of all possible errors that can be returned to the FE

**Comment by DylanTinianov** [comment]
There are 3 types of error responses:

1. GraphQL errors: invalid graphql request (this means the front end is not following the schema)
2. Server Errors: bugs that occur on the backend
3. User Errors: 
- "not authorized"
- "maximum number of 10 projects reached"



![Image](https://user-images.githubusercontent.com/19377621/206763774-fdd8cb69-a5b2-4ba4-8114-6439c1c6376c.png)
![Image](https://user-images.githubusercontent.com/19377621/206763773-7a3348b2-c335-4955-aa71-7a2e97f6784f.png)
![Image](https://user-images.githubusercontent.com/19377621/206763772-f17fec78-5f5e-46f1-80f1-3a8e77416276.png)
