### ISSUE TITLE
update UpdatedAt when project changes

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground-api#126]
When any part of a project gets updated change `UpdatedAt` 

Example:
user creates a project with 5 contracts. In this case the project's `UpdatedAt` property gets set correctly.
Then user updates one of the contracts contents and sends a `CreateContractTemplate` mutation to update the contract. In this case the Project's `updatedAt` does not get updated.

**Comment by DylanTinianov** [comment]
- Also update this time when a project is accessed, so we can get metrics on stale projects
