### ISSUE TITLE
Revisit database transactions handling

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-playground-api#131]
There are a couple of places in the codebase that wouldn't well handle database errors since they are not part of the same transaction on the database we would get data that is broken. 
We need to make sure that all places that call multiple database functions do so inside same transaction, but at the same time, we don't want to change the API too much and also don't want to expose too much implementation detail. 
We could put the transaction on the request context itself and then commit the transaction at the end but we would like to have more control over the transaction so I propose the following pattern:
Create an additional API to the database called Atomic which creates a new instance with transaction assigned and then all the methods are called on that instance. Example:
```go
func (s *SQL) Atomic(runInTransaction func(sql *SQL) error) error {
	return s.db.Transaction(func(tx *gorm.DB) error {
		return runInTransaction(&SQL{db: tx})
	})
}
```
And then in service layer you can use that for example as:
```go
	p.store.Atomic(func(sql *storage.SQL) error {
		err := sql.UpdateProject()
		if err != nil {
		    return err
		}
		
		sql.InsertTransactionExecution()
		if err != nil {
		    return err
		}
	})
```

**Comment by DylanTinianov** [comment]
Closing as a better solution was found: https://github.com/onflow/flow-playground-api/issues/144
