### ISSUE TITLE
Importing does not work after redeploying

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground-api#182]
Feedback: 

Much better UI, very poor usage. I'm attempting to test a contract which required FT, NFT, MV contracts plus my own. 

1. After adding FT and NFT, updating MV to reference 0x01 or any account for that matter, **it can't import from other account**. 

2. Also, the **contracts move around the list** after attempts to deploy. 

"Redeployment seems to fudge everything. Good effort, unusable result. Look forward to the upgrades."

**Comment by DylanTinianov** [comment]
This is a larger issue related to https://github.com/onflow/flow-playground/issues/556
Going to close this for now to avoid duplication.
