### ISSUE TITLE
Hexadecimal integer literals get corrupted

### ISSUE THREAD

**Issue by gunnark-ab** [onflow/flow-playground-api#201]
**Describe the bug**

When returning 0x1 cast to Int from a Script, the Playground shows the result value as 5.

When Cadence code contains a hexadecimal integer literal like `0x1`, it gets corrupted and evaluates to the number + 4 (number of accounts).

**To Reproduce**

1. Run `pub fun main(): Int { return 0x1 }` as a script
2. The returned result is:

  ```json
  {"value":"5","type":"Int"}
  ```

**Expected behavior**

- The result should be:

  ```json
  {"value":"1","type":"Int"}
  ```

- Hexadecimal integer literals do not get corrupted

**Screenshots**

<img width="420" alt="Screenshot_2023-02-16_at_12 40 26_PM" src="https://user-images.githubusercontent.com/51661/219284760-65b44b7b-aad4-47e8-a3bb-73fed2f503e2.png">

**Environment**

- OS: macOS Big Sur, 11.6.6
- Browser: Chrome, 109.0.5414.119 (Official Build) (x86_64)

**Reason**

Address replacement logic in https://github.com/onflow/flow-playground-api/blob/f4b28c178641940b2294391eda1637d3d17c8622/adapter/address.go#L50-L70 should only apply to imports, not integer literals

**Comment by turbolent** [comment]
Related:
- onflow/flow-go#2812
- #125

**Comment by sideninja** [comment]
@DylanTinianov can you take a look at this, it probably is coming form the address adapters.

**Comment by DylanTinianov** [comment]
> @DylanTinianov can you take a look at this, it probably is coming form the address adapters.

I'll look into this asap.

**Comment by turbolent** [comment]
Happy to help here. Is the address adjustment logic trying to only adjust addresses in imports, or any address in the code?

```cadence
import 0x1 // address in import

pub fun main(): Address {
    let number = 0x1 // integer literal, not an address

    return 0x1 // address value
}
```

**Comment by sideninja** [comment]
The translation happens here https://github.com/onflow/flow-playground-api/blob/master/adapter/address.go 
If I remember correctly it should do that in many different places. Probably there is a miss tho.

**Comment by DylanTinianov** [comment]
Currently this is an edge case we don’t plan on supporting in this version of Playground, but will be fixed in Playground v2. Sorry for any inconvenience this has caused!

**Comment by bluesign** [comment]
@DylanTinianov If v1 has some more time to live, I can make a quick PR to emulator to skip N addresses when bootstrapping.
