### ISSUE TITLE
Support new import syntax

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#208]
**Is your feature request related to a problem? Please describe.**
Playground v2 should not have to deal with address translation. Currently on v1, there is an issue in address translation where all hexadecimal values are translated (regardless of being an import or not). 

**Solution**
The best solution for this is to only use the new import syntax in v2 and have no address translation at all.
- The frontend should show accounts as names rather than addresses
- Maintain a flow.json file to resolve imports rather than translating
- Use flowkit for supporting the new import syntax

This will also allow for a smoother transition from Playground to local development as the flow.json file would also be exported and so imports will work the same.

Fixes this issue for v2: https://github.com/onflow/flow-playground-api/issues/201

**Comment by bluesign** [comment]
Problem is; it is not only imports. `getAccount(0x2)` still needs translation, likewise for example if script is getting an `Address` parameter.

**Comment by sideninja** [comment]
@bluesign we can still show addresses for each account but they won't be as important (beside few edge cases which you mention). This is not just about translation but also about making the playground experience more similar to local.
