### ISSUE TITLE
Some String's built-in functions do not work on Cadence playground

### ISSUE THREAD

**Issue by SnowyField1906** [onflow/flow-playground-api#216]
**Describe the bug**
- There are String's built-in functions which do not work on Cadence playground, but on testnet, they still work
- Some may be mentioned as: `String.fromCharacters`, `String.fromUTF8` and `T.fromString`

**To Reproduce**
On playground:
![image](https://user-images.githubusercontent.com/87925000/224773551-36697c85-dca2-46bf-a052-1bae3780a674.png)

**Expected behavior**
On VSCode extension (v1.2.0):
![image](https://user-images.githubusercontent.com/87925000/224773871-e149f90c-831a-4eef-9fec-5a98e2cb04b9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Cadence v0.36.0, Playground API v2.0.13

**Comment by jribbink** [comment]
fixed
