### ISSUE TITLE
Enable variable account count

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-playground-api#22]
## Description
We would like to enable different number of accounts per projects to allow contracts, which require big number of import dependencies - `TopShot` for example.
But we don't want to simply increase number of accounts available, cause it will bloat the sidebar - especially on smaller screens.
When solved, this issue shall enable https://github.com/onflow/flow-playground/issues/133 on front-end.

## Solution
We will create additional field on the Project, which will hold current number of active accounts.

## Possible Issues
One scenario, which can lead to some interaction issues would be if user would enable new accounts, then deploy contract to one of them and then reduce number back to initial number. If there will be imports from that address in other contracts, transactions or scripts, language client will not report any issues :man_shrugging:

**Comment by neilZon** [comment]
What is the status of this? I was wondering if I could take this issue
