### ISSUE TITLE
Bootstrap deployment of standard contracts

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#239]
**Is your feature request related to a problem? Please describe.**
Have all standard contracts deployed automatically so users can simply import them into their projects without copy pasting the code.

- Could extend the Playground bootstrap of emulator/ blockchain and add deployment of contracts in there as well

**Comment by bluesign** [comment]
This can be handled with snapshot or with https://github.com/onflow/flow-go/issues/2812
