### ISSUE TITLE
Critical CPU Usage causing slow down

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground-api#246]
Create project took 1.4 seconds
![image](https://user-images.githubusercontent.com/3970376/230647095-e6dbda1b-4f80-4a30-acc3-7fcfa44a3bdc.png)

There seems to be a slowdown on the backend. deployments and running transactions are taking much longer than before.

**Comment by DylanTinianov** [comment]
Increased CPU limits on deployment

**Comment by DylanTinianov** [comment]
Looking into what's causing high CPU usage

**Comment by bluesign** [comment]
probably index related

**Comment by DylanTinianov** [comment]
Database was updated, CPU usage looks normal again. I will keep monitoring this, but closing for now.
