### ISSUE TITLE
Change database indexes to integers

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#254]
**Is your feature request related to a problem? Please describe.**
Currently the database models are indexed by uuid, which is bad for performance. We should change the implementation to have integer indexes instead.

**Describe the solution you'd like**
Rework internal db models with integer indexes.
We must also create a model converter to migrate the data to the new models. Make sure to test this thoroughly on Staging as well.

**Comment by bluesign** [comment]
> Currently the database models are indexed by uuid, which is bad for performance. 

Don't know the specifics but this is not true in general. Also I fail to see indexes in the project, why it is not managed via gorm ?
