### ISSUE TITLE
Fix Contract Redeployment

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#255]
**Describe the bug**
If a contract is deployed which places a resource onto an account, redeploying this contract will fail. Currently, a transaction will delete the contract. However, this does not delete the transaction which places the resource onto the account. Redeploying the contract will now fail due to the resource already being on the account. This causes projects to not load due to being in this invalid state.

Issue on Sentry: https://dapperlabs.sentry.io/issues/4083790981/?project=6398442&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

- Flow-CLI has the same issue: https://github.com/onflow/flow-cli/issues/986

### Solution
Create a mapping of deployed Contracts to their corresponding block height. When a contract is redeployed, we then reset the block height to before the contract was last deployed. This clears all actions after the initial deployment of the contract which solves the issue of having invalid resources left on accounts due to removing or editing a contract.

We will need to delete all transaction executions + contract deployments in the database past after and including this block height/ index, and then deploy the contract again.

In the database modify ContractDeployments to include block height:

```
ContractDeployment {
	File
	Address     Address        `gorm:"serializer:json"`
	BlockHeight int            `json:"blockHeight"`
	Errors      []ProgramError `gorm:"serializer:json"`
	Events      []Event        `gorm:"serializer:json"`
	Logs        []string       `gorm:"serializer:json"`
}
```

Now instead of resetting the state completely when a user updates a contract, we just rollback to the previous state before their contract was deployed initially.

**Comment by devbugging** [comment]
Related: https://github.com/onflow/flow-cli/issues/986
