### ISSUE TITLE
Codebase architecture refactor

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#41]
Currently the code is organized and connected roughly as follows:

<img width="850" alt="Playground API Current" src="https://user-images.githubusercontent.com/19377621/188004204-9e8cb723-08c8-492b-af8a-7b79f5449fb7.png">

This is confusing with poor abstraction. The server is doing too much work (look at the main function).
Also, currently most modules are in top-level folders which makes control flow difficult to understand.

Here are my suggestions on how to improve the architecture:

<img width="612" alt="Screen Shot 2022-09-20 at 9 23 25 AM" src="https://user-images.githubusercontent.com/19377621/191312444-df8e3f91-9f6e-49e1-8315-847fef60e5d9.png">

<img width="359" alt="Playground API Improvements - globals" src="https://user-images.githubusercontent.com/19377621/188004525-ffb9fd79-56d5-4f6e-b8e2-5dea279e6239.png">

The implementation is relatively straight forward, and won't take long. This will improve maintainability, and abstract functionality into a more modular approach.

**Comment by psiemens** [comment]
Thanks for creating these diagrams and proposing a new architecture! Your proposed design makes a lot of sense to me.

One note: the `client` package is only used by the tests in `playground_test.go` but I don't think it's immediately clear that it's only for testing. I wonder if there's a way to avoid that confusion.

You'll noticed that `playground_test.go` is a bit of a behemoth as well, but I'd recommend keeping the test code as untouched as possible during this refactor in order to confidently check for regressions.

**Comment by DylanTinianov** [comment]
> Thanks for creating these diagrams and proposing a new architecture! Your proposed design makes a lot of sense to me.
> 
> One note: the `client` package is only used by the tests in `playground_test.go` but I don't think it's immediately clear that it's only for testing. I wonder if there's a way to avoid that confusion.
> 
> You'll noticed that `playground_test.go` is a bit of a behemoth as well, but I'd recommend keeping the test code as untouched as possible during this refactor in order to confidently check for regressions.

Yeah I realized that about the client package as well. The solution is to make a test directory and put client in there along with playground_test.go. Then later we can break playground_test.go into smaller test modules and keep them all in the same directory. Would probably also make sense to move the other tests there as well (ex. embeds_test.go, migrate_test.go, etc).
