### ISSUE TITLE
Update logging & Sentry

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#71]
## Describe the feature in a few words
We need to create custom errors to show the user which hides the backend details.

## What will be the end result of this change?
The result of this change will allow the frontend to only display error messages that the user can understand and act upon. For example, database errors should just the show user "Something went wrong, please try again later". The details should however be piped into Sentry.

## Is there any previous work that needs to be completed before making this change?
No previous work is required, but refactors will likely help determine the structure of errors.

## Which components will this change affect?
This change will effect our Middlewares for Error handling and Sentry reporting.

**Comment by sideninja** [comment]
I was thinking about doing this in a way that we are wrapping errors in our custom errors so handler for graphQL can in one place report those to sentry as they are important whereas some other errors might not be. For example if there's an input problem with argument we don't report that to the sentry we just report to the user, if the error is insert in db wasn't successful that we need to send to sentry and only show to user there was an API error. If we do it as I said we can have one place to handle that.
