### ISSUE TITLE
Simulate tests with replicas

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-playground-api#86]
There were a lot of issues that were coming from the fact our current test doesn't test against the environment with replicas. 

We need to create a couple of E2E tests that test against such an environment. My suggestion is to create a couple of tests in a setup where you spawn up two servers and create a simple random load balancer between them. Do some discovery if there's any existing work or practices to do that in Go. 

There might even be a better approach by just creating two instances of existing client https://github.com/onflow/flow-playground-api/blob/8056249f84304ea0242420dc747a99d01c358178/playground_test.go#L2545 and just programmatically switch using each for executing those tests.

I would then test just couple of scenarios:
- Executing couple of transactions, but distribute the requests between replicas
- Deploying couple of contract, but distribute the requests between replicas
- Deploy contract but redeploy on another replica

**Comment by DylanTinianov** [comment]
While creating tests I found that replicas using the cached emulator have previous deployed contracts instead of grabbing the newest. When rebuilding the missing executions on the cached emulator, the deployed code is not updated. This could be related to #85

**Comment by sideninja** [comment]
Are you able to reproduce this issue? Let's discuss it on a call, I'm not sure how it would occur since if the contract has been redeployed the whole state gets cleared, so it shouldn't have any executions to rebuild the state in the first place.
