### ISSUE TITLE
Improve content adapters for address translation

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-playground-api#87]
Currently, content adaptors just find addresses with simple regex detecting addresses, which finds also addresses in strings and change them, making the logs misbehave if they have some logs targeting the address. 

An example problematic script content:
```
import Foo from 0x01 // should be replaced
getAccount(0x02) // should be replaced
log("hey 0x02") // shouldn't be replaced
```

Improve the code that handles that, but FIRST write a test suite that asserts functioning and confirms the bug and then do the change. It's really important to not break the current implementation. Also, don't go down the path of using the Cadence parser because I did that before but the problem becomes how the addresses are stored in the parser which doesn't match source addresses so you will have no way of replacing them in source code.

**Comment by DylanTinianov** [comment]
Do we want to ignore cases where we have this sort of regex:  ("* 0x0* *")?

**Comment by sideninja** [comment]
Yes, the above regex is not a valid address since it's only containing with 0

**Comment by DylanTinianov** [comment]
Address translation was removed.
