### ISSUE TITLE
Implement "Get Project List" Endpoint

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#88]
## Describe the feature few words
This feature will enable the frontend to ask for a list of projects for a given user.

## What will be the end result of this change?
The end result of this change will enable the front end to easily implement their project list user view.
- Enforce maximum limit of 10 projects per user

## Is there any previous work that needs to be completed before making this change?
No previous work is required.

## Which components will this change effect?
- This change will effect the backend API by providing more functionality.
- Schema additional query for projectList
- Schema additional mutation for deleteProject

**Comment by sideninja** [comment]
Limit of 10 projects per user.
