### ISSUE TITLE
Refactor the API for new features

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-playground-api#93]
## Describe the feature few words
Implement API changes from the redesign and optimization work.

## What will be the end result of this change?
Changed GraphQL APIs that will provide better interactions with the playground and support new features. 

## Is there any previous work that needs to be completed before making this change?
- Redesign and optimise APIs #92 
- Implement file entity #72 

Which components will this change affect?
The frontend API implementation.

**Comment by DylanTinianov** [comment]
Duplicate
